### ISSUE TITLE
Error when trying to create "slopes" schema

### ISSUE THREAD

**Issue by hholzgra** [lonvia/waymarked-trails-site#260]
```
$ ./makedb.py slopes create
Traceback (most recent call last):
  File "./makedb.py", line 122, in <module>
    mapdb = mapdb_class(options)
  File "/home/maposmatic/waymarked-trails-site/db/routes.py", line 44, in __init__
    osgende.MapDB.__init__(self, options)
  File "/usr/local/lib/python3.5/dist-packages/osgende/mapdb.py", line 59, in __init__
    self.tables = self.create_tables()
  File "/home/maposmatic/waymarked-trails-site/db/slopes.py", line 44, in create_tables
    tables = vars(super().create_tables())
TypeError: vars() argument must have __dict__ attribute
16-11-11 09:13:37 Used memory by index: 35954560592
```

This is probably related to a change in python 3.5.1 (I've got Ubuntu 16.04 with Python3 version 3.5.2 here), see e.g. http://stackoverflow.com/questions/34166469/did-something-about-namedtuple-change-in-3-5-1/34166604

So the following patch seems to fix it:

```
diff --git a/db/slopes.py b/db/slopes.py
index db87a57..530aa23 100644
--- a/db/slopes.py
+++ b/db/slopes.py
@@ -41,7 +41,7 @@ class DB(RoutesDB):
 
     def create_tables(self):
         # all the route stuff we take from the RoutesDB implmentation
-        tables = vars(super().create_tables())
+        tables = super().create_tables()._asdict()
 
         # now create the additional joined ways
         subset = and_(text(CONF.way_subset),
```

**Comment by lonvia** [comment]
I've moved parts of create_tables() in a separate function, so that the conversion from namedtuple to dict can be avoided altogether.
